<?php
/**
 * @file
 * Main module file for DFP Respond
 */

/**
 * Implements hook_menu().
 */
function dfp_respond_menu() {
  $items = array();
  $items['admin/structure/dfp_ads/respond'] = array(
    'title' => 'DFP Respond',
    'description' => 'Configure DFP Respond.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dfp_respond_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 15,
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function dfp_respond_settings_form() {
  $form = array();

  $form['dfp_respond_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Respond URL'),
    '#description' => t('The URL for the Respond script.'),
    '#default_value' => check_plain(variable_get('dfp_respond_url', 'http://responddiscovery.blob.core.windows.net/scripts/respond-discovery-placement.min.js')),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_context_registry().
 */
function dfp_respond_context_registry() {
  return array(
    'reactions' => array(
      'dfp_respond' => array(
        'title' => t('DFP Respond'),
        'plugin' => 'dfp_respond_context_reaction_respond',
      ),
    ),
  );
}

/**
 * Implements hook_context_plugins().
 */
function dfp_respond_context_plugins() {
  $plugins = array();
  $plugins['dfp_respond_context_reaction_respond'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'dfp_respond') . '/plugins',
      'file' => 'dfp_respond_context_reaction_respond.inc',
      'class' => 'dfp_respond_context_reaction_respond',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

